#!/usr/bin/env python3
"""Public-release safety gate for this repository.

The repository is PUBLIC. It was originally designed with PRIVATE-repo
assumptions, the most visible one being the `MACHINE-SPECIFIC ALLOWED`
designated-deployment-file exception. That exception is DEFUNCT in public
release mode: a public repository cannot declare a file "machine-specific
allowed" and then commit host facts, because the file is world-readable.

Threat model (see RULES.md R2):

    IF REPOSITORY_VISIBILITY == PUBLIC
        SECRET / LOCAL_IDENTITY   -> forbidden everywhere
        MACHINE_FINGERPRINT       -> forbidden in committed public artifacts
                                     unless it is a generic placeholder or
                                     ${HOME}-relative portable documentation
        PUBLIC_ACCOUNT_IDENTITY   -> allowed only when intentionally part of
                                     project identity (see
                                     PUBLIC_PROJECT_IDENTITY below)
        PRIVATE_MACHINE_RECOVERY  -> must stay local-only / git-ignored /
                                     external private storage

    IF REPOSITORY_VISIBILITY == PRIVATE
        MACHINE_FINGERPRINT is allowed ONLY inside a designated deployment
        profile (under `deployment/`, carrying the marker). Ordinary
        governance / audit / README files stay forbidden: private visibility
        is not a blanket exemption.

Design invariants (external audit F1 / F2 / F5 / F6 / F7):

  * NO whole-file scanner self-exemption. This file is scanned like any other
    file, in both tree and history mode. Detector regexes are written so their
    own source text cannot match them (a character class breaks the literal),
    and every synthetic fixture is composed at run time so no sensitive
    literal exists in this source. The incident this gate repairs was
    validator source leaking host identity; exempting validator source from
    the scan would reproduce that incident.
  * SECRET / LOCAL_IDENTITY detection is content-based, never gated on a file
    extension allowlist. Extensionless configuration, dotfiles, container and
    build recipes are exactly where credentials live.
  * CURRENT_TREE means PUBLIC CANDIDATE SURFACE, not "whatever is on this
    disk" (F5). Enumeration is Git-aware — tracked files plus untracked
    non-ignored files, i.e. `git ls-files --cached --others
    --exclude-standard`. Git-ignored machine-local artifacts (the local-only
    recovery profile, generated bytecode, caches) are deliberately NOT part of
    the public candidate surface: they are never published, and pulling them
    in would both contradict the local-only profile contract and make scope
    nondeterministic between a workstation and CI. Outside a Git repository
    the enumeration falls back to the filesystem and says so explicitly in
    the reported scope.
  * A candidate PATH has up to TWO publishable CONTENTS, and Git publishes the
    staged one (F7). `git commit` writes INDEX content, so a secret can be
    staged and then wiped from the working tree; scanning only the working
    tree would pass that branch and push it to a public remote, where CI
    afterwards is too late. Both surfaces are therefore inspected: the INDEX
    blob (what the next commit publishes) and the working-tree file
    (publishable change not yet staged, including untracked non-ignored
    files). When both carry the same content the path is scanned once; when
    they differ, both are reported, labelled `index:` / `worktree:`. A tracked
    symlink is not skipped: Git publishes its TARGET STRING as blob content,
    so that string is scanned and the target file is never dereferenced.
  * An input the gate could not read is NOT a pass (F6), and the read is
    bounded in the literal sense (F7): SIZE IS DETERMINED BEFORE CONTENT IS
    MATERIALIZED — from filesystem metadata for working-tree candidates and
    from `git cat-file --batch-check` object metadata for staged blobs. A
    CURRENT_TREE candidate above the cap fails closed as
    UNSCANNED_OVERSIZE_PUBLIC_FILE with its content withheld and never read
    at all; READ_METER makes that mechanically checkable. This is a bounded
    read, NOT streaming: nothing is inspected in partial windows. History mode
    keeps oversize blobs as measured/skipped evidence, which is why its
    verdict is explicitly qualified to the scanned reachable text objects and
    never claims a clean full history.

Execution contract (one file, four modes):

    python3 scripts/validate_public_release.py                    # CURRENT_TREE_SCAN
    python3 scripts/validate_public_release.py --history          # GIT_HISTORY_SCAN
    python3 scripts/validate_public_release.py --commit-metadata  # HEAD identity gate
    python3 scripts/validate_public_release.py --selftest         # synthetic tests

Environment:

    PUBLIC_RELEASE=1   force public mode (deterministic, no GitHub API needed)
    PUBLIC_RELEASE=0   force private mode (designated exception available)
    unset              default PUBLIC (this repository is public)

Exit 0 = clean, 1 = violations found. Never prints a credential value, a host
login name, or a non-canonical account handle.
"""
from __future__ import annotations

import os
import re
import stat as statmod
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Content classification, replacing the former extension allowlist (F2).
# The cap is enforced from SIZE METADATA BEFORE any content is materialized
# (F7): `lstat().st_size` for working-tree candidates, `cat-file --batch-check`
# for staged blobs.
MAX_SCAN_BYTES = 2 * 1024 * 1024          # bounded read cap per candidate/blob
BINARY_SNIFF_BYTES = 8192                 # bytes inspected for text/binary
NONTEXT_RATIO_LIMIT = 0.30
_NONTEXT_BYTES = bytes(range(0, 7)) + b"\x0b\x0c" + bytes(range(14, 32)) + b"\x7f"

# F6 — fail-closed classification for a public candidate the gate could not
# inspect. Unscanned is not clean.
OVERSIZE_SEVERITY = "UNSCANNED_OVERSIZE_PUBLIC_FILE"
OVERSIZE_RULE = "SIZE_CAP_EXCEEDED"

# F5 — how the CURRENT_TREE candidate surface was enumerated. Reported, not
# assumed, so local and CI scope differences are explainable.
ENUM_GIT = "git_ls_files_cached_others_exclude_standard"
ENUM_FS_FALLBACK = "filesystem_fallback_not_a_git_worktree_root"
ENUM_HISTORY = "git_cat_file_batch_all_objects"

# F7 — a candidate path carries up to two publishable contents. Labels are used
# ONLY when the two differ, so an unmodified path keeps its plain report path.
SURFACE_INDEX = "index:"
SURFACE_WORKTREE = "worktree:"

# F7 — sentinel for "size cap exceeded, content deliberately NOT read". Distinct
# from None (which means "no such surface" / "unreadable").
OVERSIZE: object = object()

# F7 — mechanical proof that the read is bounded: every byte of candidate
# content this scanner materializes is counted here. An oversize candidate must
# leave the counter untouched, which the self-tests assert.
READ_METER: dict[str, int] = {"bytes_materialized": 0}

# --------------------------------------------------------------------------
# Intentional public project identity (F4). Deliberately the ONLY identity
# concept in this file: this is a gate, not an identity-management framework.
# --------------------------------------------------------------------------
PUBLIC_PROJECT_IDENTITY = "FlapPearLabs"
NOREPLY_HOST = "users.noreply.github.com"
NOREPLY_RX = re.compile(
    r"(?:(?P<uid>\d+)\+)?(?P<handle>[A-Za-z0-9][A-Za-z0-9\-]{0,38})@"
    + NOREPLY_HOST.replace(".", r"\."),
    re.I,
)

# --------------------------------------------------------------------------
# TIER A — forbidden everywhere, in every visibility mode.
# Each regex is written so that its own source line cannot match it.
# --------------------------------------------------------------------------
TIER_A_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("GITHUB_PAT", re.compile(r"gh[pousr]_[A-Za-z0-9]{20,}")),
    ("GITHUB_FINE_GRAINED_PAT", re.compile(r"github_pat_[A-Za-z0-9_]{20,}")),
    ("AWS_ACCESS_KEY", re.compile(r"AKIA[0-9A-Z]{16}")),
    ("SLACK_TOKEN", re.compile(r"xox[abposr]-[A-Za-z0-9-]{10,}")),
    ("OPENAI_STYLE_KEY", re.compile(r"sk-[A-Za-z0-9]{20,}")),
    ("GOOGLE_API_KEY", re.compile(r"AIza[0-9A-Za-z_\-]{35}")),
    ("PRIVATE_KEY_HEADER", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY")),
    ("GENERIC_BEARER", re.compile(r"(?i)bearer\s+[A-Za-z0-9._\-]{20,}")),
    ("COOKIE_ASSIGNMENT", re.compile(r"(?i)cookie\s*=\s*[A-Za-z0-9._\-]{16,}")),
    ("PASSWORD_ASSIGNMENT", re.compile(r"(?i)password\s*=\s*\S{8,}")),
    # LOCAL_IDENTITY: concrete host login directories. A placeholder such as
    # /Users/<LOCAL_OS_USERNAME>/ deliberately does NOT match, because '<' is
    # outside the trailing character class.
    ("WIN_USER_HOME", re.compile(r"(?i)[A-Za-z]:[\\/]+Users[\\/]+[A-Za-z0-9._\-]+")),
    ("UNIX_USER_HOME", re.compile(r"/(?:Users|home)/[A-Za-z0-9._\-]+")),
]

SECRET_RULES = {
    "GITHUB_PAT", "GITHUB_FINE_GRAINED_PAT", "AWS_ACCESS_KEY", "SLACK_TOKEN",
    "OPENAI_STYLE_KEY", "GOOGLE_API_KEY", "PRIVATE_KEY_HEADER",
    "GENERIC_BEARER", "COOKIE_ASSIGNMENT", "PASSWORD_ASSIGNMENT",
}

# --------------------------------------------------------------------------
# TIER B — machine fingerprint. Forbidden in PUBLIC artifacts; in PRIVATE mode
# forbidden everywhere except a designated deployment profile.
# --------------------------------------------------------------------------
TIER_B_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("LOCALHOST_ENDPOINT", re.compile(r"(?:127\.0\.0\.1|localhost|0\.0\.0\.0):[0-9]{2,5}")),
    # `[b]` breaks the literal so this detector cannot match its own source.
    ("HOST_PACKAGE_PREFIX", re.compile(r"/opt/home[b]rew/")),
    # Requires an actual endpoint: a scheme or a host:port. A documented
    # template leaves nothing matchable after placeholder stripping.
    ("PROXY_ENV_VALUE",
     re.compile(r"(?i)\bhttps?_proxy\s*[=:]\s*(?:https?://|[\w.\-]+:\d+)\S*")),
]

# Generic / portable forms that are allowed documentation, never a host fact.
PLACEHOLDER_SPANS = [
    re.compile(r"<[A-Z][A-Z0-9_]{2,}>"),
    re.compile(r"\$\{[A-Za-z_][A-Za-z0-9_]*\}"),
    re.compile(r"\$\([^)]*\)"),
]

# The historical private-repo escape hatch. Retained so that (a) private mode
# keeps its documented, NARROW semantics and (b) the test suite can prove it
# does not bypass public mode.
DESIGNATED_MARKER = "MACHINE-SPECIFIC ALLOWED"
DESIGNATED_DIR = "deployment"


def public_mode() -> bool:
    """Deterministic, offline: PUBLIC_RELEASE env wins, default PUBLIC."""
    raw = os.environ.get("PUBLIC_RELEASE")
    if raw is None:
        return True
    return raw.strip() not in ("0", "false", "False", "no")


# --------------------------------------------------------------------------
# Output safety: never emit a secret value, a real login name, or a
# non-canonical account handle.
# --------------------------------------------------------------------------
def _redact_noreply(m: re.Match[str]) -> str:
    if m.group("handle").lower() == PUBLIC_PROJECT_IDENTITY.lower():
        return m.group(0)
    return "<SECONDARY_GITHUB_HANDLE>@" + NOREPLY_HOST


def sanitize(text: str) -> str:
    text = re.sub(r"(/(?:Users|home)/)[A-Za-z0-9._\-]+",
                  r"\1<LOCAL_OS_USERNAME>", text)
    text = re.sub(r"(?i)([A-Za-z]:[\\/]+Users[\\/]+)[A-Za-z0-9._\-]+",
                  r"\1<LOCAL_OS_USERNAME>", text)
    return NOREPLY_RX.sub(_redact_noreply, text)


@dataclass
class Violation:
    severity: str      # SECRET | LOCAL_IDENTITY | MACHINE_FINGERPRINT
    rule: str
    path: str
    lineno: int
    excerpt: str       # already sanitized / redacted

    def render(self) -> str:
        return f"[{self.severity}/{self.rule}] {self.path}:{self.lineno} :: {self.excerpt}"


@dataclass
class Scope:
    """Honest accounting of what was actually inspected.

    F7 adds per-surface accounting for CURRENT_TREE mode, with the checkable
    invariant

        blobs_total == surfaces_index + surfaces_worktree - deduped_paths

    where `deduped_paths` counts candidate paths whose two surfaces carried the
    same content and were therefore scanned once. `eol_only_dedup` is the subset
    of those whose raw bytes differed only in line endings (`core.autocrlf`
    translation), recorded so that normalization is reported rather than hidden.
    """
    enumeration: str = "unset"
    refs: int = 0
    objects_total: int = 0
    blobs_total: int = 0
    text_scanned: int = 0
    skipped_binary: int = 0
    skipped_oversize: int = 0
    skipped_unreadable: int = 0
    surfaces_index: int = 0
    surfaces_worktree: int = 0
    deduped_paths: int = 0
    eol_only_dedup: int = 0
    notes: list[str] = field(default_factory=list)

    def render(self, kind: str) -> str:
        return (f"{kind}_SCOPE enum={self.enumeration} refs={self.refs} "
                f"objects={self.objects_total} "
                f"blobs={self.blobs_total} text_scanned={self.text_scanned} "
                f"skipped_binary={self.skipped_binary} "
                f"skipped_oversize={self.skipped_oversize} "
                f"skipped_unreadable={self.skipped_unreadable} "
                f"surfaces_index={self.surfaces_index} "
                f"surfaces_worktree={self.surfaces_worktree} "
                f"deduped_paths={self.deduped_paths} "
                f"eol_only_dedup={self.eol_only_dedup} "
                f"size_cap_bytes={MAX_SCAN_BYTES}")


def decode_if_text(data: bytes, scope: Scope | None = None) -> str | None:
    """Content-based text classification (F2). No extension allowlist.

    Bounded, not streaming: `data` is already capped by the caller's read
    limit. In CURRENT_TREE mode an oversize candidate never reaches this
    function at all — its size is known from metadata and the content is never
    read (F7). The residual length check here guards history mode, where a
    `cat-file --batch` record has already been consumed off the pipe and is
    recorded as measured skipped evidence.
    """
    if len(data) > MAX_SCAN_BYTES:
        if scope:
            scope.skipped_oversize += 1
        return None
    sniff = data[:BINARY_SNIFF_BYTES]
    if b"\x00" in sniff:
        if scope:
            scope.skipped_binary += 1
        return None
    if sniff:
        nontext = sum(sniff.count(b) for b in _NONTEXT_BYTES)
        if nontext / len(sniff) > NONTEXT_RATIO_LIMIT:
            if scope:
                scope.skipped_binary += 1
            return None
    if scope:
        scope.text_scanned += 1
    return data.decode("utf-8", "replace")


def strip_placeholders(line: str) -> str:
    for rx in PLACEHOLDER_SPANS:
        line = rx.sub(" ", line)
    line = line.replace("~", " ").replace("$HOME", " ")
    return line


def report_path(path: str) -> str:
    """Strip surface/history labels back to the repository-relative path.

    Report labels carry provenance (`index:`, `worktree:`, `history:<sha>:`);
    policy decisions must be made on the underlying path, otherwise adding a
    provenance label would silently change which rules apply.
    """
    norm = path.replace("\\", "/")
    if norm.startswith("history:"):
        return norm.split(":", 2)[-1]
    for prefix in (SURFACE_INDEX, SURFACE_WORKTREE):
        if norm.startswith(prefix):
            return norm[len(prefix):]
    return norm


def is_designated(path: str, text: str) -> bool:
    """Designated private machine-recovery profile: path AND header marker."""
    norm = report_path(path)
    head = "\n".join(text.splitlines()[:10])
    return norm.startswith(DESIGNATED_DIR + "/") and DESIGNATED_MARKER in head


def scan_text(path: str, text: str) -> list[Violation]:
    out: list[Violation] = []
    # F3: private visibility is not a blanket exemption. Tier B is skipped ONLY
    # for a designated deployment profile, and only when not in public mode.
    tier_b_exempt = (not public_mode()) and is_designated(path, text)
    for lineno, raw in enumerate(text.splitlines(), 1):
        # TIER A is unconditional: no placeholder, marker or visibility mode can
        # excuse a credential or a concrete local login directory.
        for rule, rx in TIER_A_PATTERNS:
            if rx.search(raw):
                if rule in SECRET_RULES:
                    sev, excerpt = "SECRET", "<REDACTED: value withheld>"
                else:
                    sev = "LOCAL_IDENTITY"
                    excerpt = sanitize(raw.strip())[:160]
                out.append(Violation(sev, rule, path, lineno, excerpt))
        if tier_b_exempt:
            continue
        probe = strip_placeholders(raw)
        for rule, rx in TIER_B_PATTERNS:
            if rx.search(probe):
                out.append(Violation("MACHINE_FINGERPRINT", rule, path, lineno,
                                     sanitize(probe.strip())[:160]))
    return out


def git_worktree_root(root: Path) -> bool:
    """True only when `root` is itself the top level of a Git worktree.

    Deliberately strict: if `root` merely sits *inside* some other repository,
    `git ls-files` would answer for that repository, so the Git-aware
    enumeration must not be claimed.
    """
    proc = subprocess.run(["git", "-C", str(root), "rev-parse", "--show-toplevel"],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        return False
    top = proc.stdout.strip()
    if not top:
        return False
    try:
        return Path(top).resolve() == root.resolve()
    except OSError:
        return False


def git_candidate_paths(root: Path) -> list[str] | None:
    """PUBLIC candidate surface (F5): tracked + untracked non-ignored paths.

    Equivalent to `git ls-files --cached --others --exclude-standard`. Returns
    None when `root` is not a Git worktree root, so the caller can fall back
    and classify that fallback explicitly.
    """
    if not git_worktree_root(root):
        return None
    proc = subprocess.run(
        ["git", "-C", str(root), "ls-files", "-z",
         "--cached", "--others", "--exclude-standard"],
        capture_output=True)
    if proc.returncode != 0:
        return None
    seen: dict[str, None] = {}
    for raw in proc.stdout.split(b"\x00"):
        if not raw:
            continue
        rel = raw.decode("utf-8", "surrogateescape").replace("\\", "/")
        seen.setdefault(rel, None)
    return sorted(seen)


def git_index_entries(root: Path) -> dict[str, list[tuple[str, str]]]:
    """rel -> [(mode, blob_sha), ...] for the Git INDEX (F7).

    The index is what `git commit` publishes, so it is a first-class scan
    surface. Every stage is kept: an unmerged path has stages 1/2/3 and no
    stage 0, and each of those contents can end up in the resolved commit, so
    none of them may be silently dropped.
    """
    proc = subprocess.run(["git", "-C", str(root), "ls-files", "-z", "--stage"],
                          capture_output=True)
    if proc.returncode != 0:
        return {}
    staged: dict[str, list[tuple[str, str, str]]] = {}
    for raw in proc.stdout.split(b"\x00"):
        if not raw:
            continue
        meta, _, path = raw.decode("utf-8", "surrogateescape").partition("\t")
        parts = meta.split()
        if len(parts) < 3 or not path:
            continue
        mode, sha, stage = parts[0], parts[1], parts[2]
        staged.setdefault(path.replace("\\", "/"), []).append((mode, sha, stage))
    out: dict[str, list[tuple[str, str]]] = {}
    for rel, entries in staged.items():
        stage0 = [(m, s) for m, s, st in entries if st == "0"]
        out[rel] = stage0 if stage0 else [(m, s) for m, s, _ in entries]
    return out


def git_blob_sizes(root: Path, shas: set[str]) -> dict[str, int]:
    """Blob sizes from `cat-file --batch-check`: METADATA ONLY (F7).

    Deliberately separate from reading: the cap must be enforced before any
    staged content is materialized.
    """
    if not shas:
        return {}
    proc = subprocess.run(["git", "-C", str(root), "cat-file", "--batch-check"],
                          input=("\n".join(sorted(shas)) + "\n").encode(),
                          capture_output=True)
    sizes: dict[str, int] = {}
    for line in proc.stdout.decode("utf-8", "replace").splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[1] == "blob":
            try:
                sizes[parts[0]] = int(parts[2])
            except ValueError:
                continue
    return sizes


def read_blob_bounded(root: Path, sha: str, size: int) -> bytes | object | None:
    """Materialize a staged blob only when Git-reported size is under the cap.

    Returns bytes, OVERSIZE (content never requested), or None (unreadable).
    """
    if size > MAX_SCAN_BYTES:
        return OVERSIZE
    proc = subprocess.run(["git", "-C", str(root), "cat-file", "blob", sha],
                          capture_output=True)
    if proc.returncode != 0:
        return None
    data = proc.stdout
    READ_METER["bytes_materialized"] += len(data)
    if len(data) > MAX_SCAN_BYTES:          # metadata/content disagreement
        return OVERSIZE
    return data


def read_worktree_bounded(p: Path) -> tuple[str, bytes | None, int]:
    """Bounded working-tree read: SIZE FIRST, content only under the cap (F7).

    Returns (kind, payload, size) with kind in
    ok | symlink | oversize | missing | nonregular | unreadable.

    A symlink yields its TARGET STRING — the bytes Git publishes for it — and
    the target file is never dereferenced, so a link pointing at a concrete
    host path is judged on what would actually be published.
    """
    try:
        st = p.lstat()
    except OSError:
        return ("missing", None, 0)
    if statmod.S_ISLNK(st.st_mode):
        try:
            target = os.readlink(p)
        except OSError:
            return ("unreadable", None, 0)
        raw = target.encode("utf-8", "surrogateescape")
        if len(raw) > MAX_SCAN_BYTES:
            return ("oversize", None, len(raw))
        READ_METER["bytes_materialized"] += len(raw)
        return ("symlink", raw, len(raw))
    if not statmod.S_ISREG(st.st_mode):
        return ("nonregular", None, 0)
    if st.st_size > MAX_SCAN_BYTES:
        return ("oversize", None, st.st_size)        # content never read
    try:
        with p.open("rb") as fh:
            data = fh.read(MAX_SCAN_BYTES + 1)       # capped even if it grew
    except OSError:
        return ("unreadable", None, 0)
    READ_METER["bytes_materialized"] += len(data)
    if len(data) > MAX_SCAN_BYTES:
        return ("oversize", None, len(data))
    return ("ok", data, len(data))


def _eol_normal(data: bytes) -> bytes:
    return data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def same_publishable_content(a: bytes, b: bytes) -> bool:
    """Whether two surfaces carry the same publishable content (F7 dedup).

    Byte equality, or equality after CR/LF normalization. The normalization is
    required for determinism, not convenience: with `core.autocrlf` the index
    holds LF while the checked-out file holds CRLF, so raw-byte comparison
    would report two surfaces per path on a Windows workstation and one per
    path on Linux CI. Line endings cannot conceal a credential or a host path
    from line-based detectors — both variants split into the same logical
    lines — and every such dedup is counted in `eol_only_dedup`.
    """
    return a == b or _eol_normal(a) == _eol_normal(b)


def iter_candidate_surfaces(root: Path, scope: Scope | None = None):
    """Yield (label, payload, size) for every content Git could publish (F7).

    Per candidate path there are up to two surfaces: the INDEX blob (what the
    next commit publishes) and the working-tree file (a publishable change not
    yet staged, including untracked non-ignored files). Identical content is
    scanned once under the plain path; differing content is yielded twice with
    `index:` / `worktree:` labels so the evidence says which surface failed.
    `payload` is bytes, or OVERSIZE when the cap was exceeded and the content
    was therefore never read.
    """
    rels = git_candidate_paths(root)
    if rels is None:
        if scope:
            scope.enumeration = ENUM_FS_FALLBACK
        for p in sorted(root.rglob("*")):
            if ".git" in p.parts:
                continue
            rel = str(p.relative_to(root)).replace("\\", "/")
            kind, payload, size = read_worktree_bounded(p)
            if kind in ("ok", "symlink") and payload is not None:
                if scope:
                    scope.surfaces_worktree += 1
                yield rel, payload, size
            elif kind == "oversize":
                if scope:
                    scope.surfaces_worktree += 1
                yield rel, OVERSIZE, size
            elif kind == "unreadable" and scope:
                scope.skipped_unreadable += 1
        return

    if scope:
        scope.enumeration = ENUM_GIT
    index = git_index_entries(root)
    sizes = git_blob_sizes(
        root, {sha for stages in index.values() for _, sha in stages})

    for rel in rels:
        kind, wt_payload, wt_size = read_worktree_bounded(root / rel)
        if kind == "unreadable" and scope:
            scope.skipped_unreadable += 1
        wt_present = kind in ("ok", "symlink", "oversize")
        wt_value: bytes | object | None = (
            OVERSIZE if kind == "oversize" else wt_payload)

        idx_units: list[tuple[bytes | object, int]] = []
        for _mode, sha in index.get(rel, []):
            size = sizes.get(sha, 0)
            value = read_blob_bounded(root, sha, size)
            if value is None:
                if scope:
                    scope.skipped_unreadable += 1
                continue
            idx_units.append((value, size))

        # Single staged content plus a working-tree file: the common case, and
        # the only one where dedup is meaningful.
        if len(idx_units) == 1 and wt_present and wt_value is not None:
            idx_value, idx_size = idx_units[0]
            both_oversize = idx_value is OVERSIZE and wt_value is OVERSIZE
            both_read = isinstance(idx_value, bytes) and isinstance(wt_value, bytes)
            identical = both_oversize or (
                both_read and same_publishable_content(idx_value, wt_value))
            if identical:
                if scope:
                    scope.surfaces_index += 1
                    scope.surfaces_worktree += 1
                    scope.deduped_paths += 1
                    if both_read and idx_value != wt_value:
                        scope.eol_only_dedup += 1
                yield rel, idx_value, max(idx_size, wt_size)
                continue
            if scope:
                scope.surfaces_index += 1
            yield SURFACE_INDEX + rel, idx_value, idx_size
            if scope:
                scope.surfaces_worktree += 1
            yield SURFACE_WORKTREE + rel, wt_value, wt_size
            continue

        for idx_value, idx_size in idx_units:
            if scope:
                scope.surfaces_index += 1
            yield SURFACE_INDEX + rel, idx_value, idx_size
        if wt_present and wt_value is not None:
            if scope:
                scope.surfaces_worktree += 1
            label = (SURFACE_WORKTREE + rel) if idx_units else rel
            yield label, wt_value, wt_size


def scan_tree(root: Path, scope: Scope | None = None) -> list[Violation]:
    """CURRENT_TREE_SCAN over the public candidate surface.

    F6/F7: a candidate above the read cap is a FAILURE, not a skip. It is
    reported as UNSCANNED_OVERSIZE_PUBLIC_FILE with its content withheld —
    and, since the cap is applied to size metadata, never read at all.
    """
    out: list[Violation] = []
    for label, payload, size in iter_candidate_surfaces(root, scope):
        if scope:
            scope.blobs_total += 1
        if payload is OVERSIZE or not isinstance(payload, bytes):
            if scope:
                scope.skipped_oversize += 1
            out.append(Violation(
                OVERSIZE_SEVERITY, OVERSIZE_RULE, label, 0,
                f"<NOT SCANNED: {size} bytes exceeds "
                f"size_cap_bytes={MAX_SCAN_BYTES}; content withheld>"))
            continue
        text = decode_if_text(payload, scope)
        if text is None:
            continue
        out += scan_text(label, text)
    return out


def scan_history(root: Path, scope: Scope | None = None) -> list[Violation]:
    """GIT_HISTORY_SCAN over every blob in the reachable object store.

    Deliberately separate from CURRENT_TREE_SCAN: the tree scan gates the
    publishable candidate surface, the history scan measures what is already
    immutable in the object store. Scope is recorded, not assumed: the caller
    reports how many refs/objects were actually inspected instead of claiming
    a universal clean bill.

    Oversize blobs are measured/skipped evidence here rather than a hard
    failure (F6): history cannot be "fixed" by failing a scan, so the honest
    output is `skipped_oversize` plus a verdict qualified to the scanned
    reachable text objects.
    """
    scope = scope if scope is not None else Scope()
    scope.enumeration = ENUM_HISTORY
    refs = subprocess.run(["git", "-C", str(root), "for-each-ref", "--format=%(refname)"],
                          capture_output=True, text=True)
    scope.refs = len([r for r in refs.stdout.splitlines() if r.strip()])

    paths: dict[str, str] = {}
    listing = subprocess.run(["git", "-C", str(root), "rev-list", "--objects", "--all"],
                             capture_output=True, text=True)
    for line in listing.stdout.splitlines():
        parts = line.split(" ", 1)
        if len(parts) == 2 and parts[1] and not parts[1].endswith("/"):
            paths.setdefault(parts[0], parts[1])

    out: list[Violation] = []
    proc = subprocess.Popen(
        ["git", "-C", str(root), "cat-file", "--batch-all-objects", "--batch"],
        stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    assert proc.stdout is not None
    while True:
        header = proc.stdout.readline().decode("utf-8", "replace").strip()
        if not header:
            break
        parts = header.split()
        if len(parts) < 3:
            continue
        sha, otype, size = parts[0], parts[1], int(parts[2])
        data = proc.stdout.read(size)
        proc.stdout.read(1)
        scope.objects_total += 1
        if otype != "blob":
            continue
        scope.blobs_total += 1
        text = decode_if_text(data, scope)
        if text is None:
            continue
        rel = paths.get(sha, f"unnamed-object/{sha[:8]}")
        out += scan_text(f"history:{sha[:8]}:{rel}", text)
    proc.wait()
    return out


# --------------------------------------------------------------------------
# F4 — CURRENT_HEAD_COMMIT_METADATA gate.
# --------------------------------------------------------------------------
def mask_name(value: str) -> str:
    return "<NON_CANONICAL_AUTHOR_NAME>" if value.strip() else "<EMPTY>"


def mask_email(value: str) -> str:
    value = value.strip()
    if not value:
        return "<EMPTY>"
    if NOREPLY_RX.search(value):
        return "<SECONDARY_GITHUB_HANDLE>@" + NOREPLY_HOST
    return "<NON_CANONICAL_EMAIL>"


def identity_problems(role: str, name: str, email: str, is_merge_commit: bool = False) -> list[str]:
    """Minimal check: does this identity match the intentional public one?
    
    When a commit is a legitimate Git merge commit (has multiple parents),
    the committer is legally GitHub <noreply@github.com>.
    Ordinary commits must always match PUBLIC_PROJECT_IDENTITY for both author and committer.
    """
    if is_merge_commit and role == "committer":
        if name.strip() == "GitHub" and email.strip() == "noreply@github.com":
            return []
    problems: list[str] = []
    if name.strip() != PUBLIC_PROJECT_IDENTITY:
        problems.append(f"{role}_name != PUBLIC_PROJECT_IDENTITY "
                        f"({mask_name(name)})")
    m = NOREPLY_RX.fullmatch(email.strip())
    if not m:
        problems.append(f"{role}_email is not a canonical noreply form of "
                        f"PUBLIC_PROJECT_IDENTITY ({mask_email(email)})")
    elif m.group("handle").lower() != PUBLIC_PROJECT_IDENTITY.lower():
        # The decisive rule: a matching display name must NOT launder a
        # different account handle into public commit metadata.
        problems.append(f"{role}_email handle != PUBLIC_PROJECT_IDENTITY "
                        f"({mask_email(email)})")
    return problems


def head_commit_metadata(root: Path) -> dict[str, str]:
    fmt = "%an%n%ae%n%cn%n%ce%n%p"
    proc = subprocess.run(["git", "-C", str(root), "log", "-1", f"--format={fmt}"],
                          capture_output=True, text=True)
    lines = proc.stdout.splitlines()
    if proc.returncode != 0 or len(lines) < 4:
        return {}
    parents = lines[4].split() if len(lines) > 4 else []
    return {"author_name": lines[0], "author_email": lines[1],
            "committer_name": lines[2], "committer_email": lines[3],
            "is_merge_commit": "true" if len(parents) >= 2 else "false"}


def commit_metadata_gate(root: Path) -> int:
    meta = head_commit_metadata(root)
    print("### CURRENT_HEAD_COMMIT_METADATA")
    print(f"PUBLIC_PROJECT_IDENTITY={PUBLIC_PROJECT_IDENTITY}")
    if not meta:
        print("VIOLATIONS=1")
        print("  [IDENTITY/NO_HEAD_COMMIT] unable to read HEAD commit metadata")
        return 1
    proc_p = subprocess.run(["git", "-C", str(root), "log", "-1", "--format=%p"],
                            capture_output=True, text=True)
    is_merge = len(proc_p.stdout.strip().split()) > 1
    problems = (identity_problems("author", meta["author_name"], meta["author_email"], is_merge_commit=is_merge)
                + identity_problems("committer", meta["committer_name"],
                                    meta["committer_email"], is_merge_commit=is_merge))
    print(f"VIOLATIONS={len(problems)}")
    for p in problems:
        print(f"  [PUBLIC_ACCOUNT_IDENTITY] {p}")
    if not problems:
        print(f"  author=committer={PUBLIC_PROJECT_IDENTITY} "
              f"(canonical @{NOREPLY_HOST})")
        return 0
    return 1


def main() -> int:
    args = sys.argv[1:]
    mode = "tree"
    for a in args:
        if a in ("--history", "--selftest", "--commit-metadata"):
            mode = a[2:]

    if mode == "selftest":
        return selftest(ROOT)

    if mode == "commit-metadata":
        return commit_metadata_gate(ROOT)

    if mode == "history":
        scope = Scope()
        v = scan_history(ROOT, scope)
        print_report("GIT_HISTORY_SCAN", v, scope, "HISTORY_SCAN")
        # MEASUREMENT, not a gate. Historical local-identity / machine-fingerprint
        # findings are a privacy-hygiene issue requiring an owner decision on
        # remediation; they must not auto-fail a scheduled job. A confirmed
        # credential in history is different: it demands rotation, so it fails.
        secrets = [x for x in v if x.severity == "SECRET"]
        ident = [x for x in v if x.severity == "LOCAL_IDENTITY"]
        mach = [x for x in v if x.severity == "MACHINE_FINGERPRINT"]
        print(f"HISTORY_SEVERITY SECRET={len(secrets)} "
              f"LOCAL_IDENTITY={len(ident)} MACHINE_FINGERPRINT={len(mach)}")
        print("CONFIRMED_SECRET_LEAKS="
              + ("NONE_FOUND_WITHIN_SCANNED_REACHABLE_TEXT_OBJECTS"
                 if not secrets else "FOUND_SEE_ABOVE"))
        print("HISTORY_REWRITE_REQUIRED=USER_DECISION_REQUIRED"
              if not secrets and (ident or mach) else
              "HISTORY_REWRITE_REQUIRED=STOP_OWNER_DECISION" if secrets else
              "HISTORY_REWRITE_REQUIRED=NO")
        return 1 if secrets else 0

    scope = Scope()
    v = scan_tree(ROOT, scope)
    print_report("CURRENT_TREE_SCAN", v, scope, "CURRENT_TREE")
    return 1 if v else 0


if __name__ == "__main__":
    sys.exit(main())
